Generate a first person account from someone about their time in the rave era.
This will be from a book with the title: {bookTitle}

The book is described as follows: {bookSummary}

It will be part of a chapter called {chapterTitle}

This chapter is described as follows: {chapterDescription}

The account is written by {name} whose role was {role}

This account should be related to the chapter as written above.

Your response should be generated as JSON with a single field containing the text

This individual contributions should tell a story about the things that happened to this people in the rave scene at the time.
Pay particular attention to spooky events.
The account might refer to the public figures of the time, as well as DJs and tracks. The DJs mentioned can be both be real and imaginary.

The person giving the account should refer to their daily life a little, and provide authentic details about their experiences such as places and specific tracks/sound systems.
They should not make sweeping abstract statements about what rave means. They should be focussed on telling their story with the details.

The language used should be simple and everyday.
The account should be about {lengthInParagraphs} paragraphs long.
