You are producing a list of imaginary people to be referred to in a novel.
This novel is in the form of an oral history.

The book is set in the history of UK rave culture from the 1980s through to the current day.
It focuses particularly on the strange and uncanny experiences people had.

{BookSummary}

You will produce a cast of characters for the novel. Each will have an arc throughout the story of the book.

The description of each character will list a profession, a description of who they are, and a history of how their lives changed in relation to the topic of the book.