'The Great Gatsby 2: Gatsby vs Kong' is a tragic novel about a rich man who devotes his life to fighting kaiju.
It is set in 1980s New York, at the height of the yuppie era.

The style is similar to that of Fitzgerald, but fused with an intense blast of horror.
When people initially glimpse the kaiju they should feel awe at the sight of them.
Descriptions of the kaiju should include details, noting their outrageous scale and strange bodies.

The book will feature references to actual events and popular figures of the 1980s.
{description}

The main recurring characters in the book are as follow:

{bookCast}
---

You are continuing a chapter called '{chapterTitle}'

{chapterDescription}

---
Continue from the chapter as shown below
{chapterTextSoFar}
---
The total length of this chapter should be {wordsPerChapter} words.